import { Button } from "@/components/ui/button";
import { ArrowLeftCircleIcon } from "lucide-react";

export default function ErrorPage() {
  return (
    <div className="flex flex-col items-center justify-center absolute inset-0">
      {/** Icon generated by v0*/}
      <TeapotIcon size={100} />
      <span className="text-4xl md:text-8xl text-bold">418</span>
      <span>I'm a teapot</span>
      <Button className="group mt-3">
        Go Back{" "}
        <ArrowLeftCircleIcon className="w-6 h-6 group-hover:scale-110 group-hover:-rotate-10 transition-all duration-300" />
      </Button>
    </div>
  );
}

function TeapotIcon({
  className,
  size = 24,
  strokeWidth = 2,
}: {
  className?: string;
  size?: number;
  strokeWidth?: number;
}) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth={strokeWidth}
      strokeLinecap="round"
      strokeLinejoin="round"
      className={className}
    >
      {/* Teapot body */}
      <path d="M5 9c0-1.7 1.3-3 3-3h6c1.7 0 3 1.3 3 3v4c0 1.7-1.3 3-3 3H8c-1.7 0-3-1.3-3-3V9z" />
      {/* Teapot spout - angled up for pouring */}
      <path d="M17 10l3 -2v" />
      {/* Teapot handle */}
      <path d="M5 7c-2.2 0-4 1.8-4 4s1.8 4 4 4" />
      {/* Teapot lid */}
      <line x1="9" y1="6" x2="13" y2="6" />
      <circle cx="11" cy="4.5" r="0.8" fill="currentColor" />
    </svg>
  );
}
